export const hexagramNames = [
    "乾 (Qián) - The Creative",
    "坤 (Kūn) - The Receptive",
    "屯 (Zhūn) - The Arousing",
    "蒙 (Méng) - The Gentle",
    "需 (Xū) - The Open",
    "讼 (Sòng) - The Dispute",
    "师 (Shī) - The Leading",
    "比 (Bǐ) - The Holding Together",
    "小畜 (Xiǎo Chù) - The Taming Power of the Small",
    "履 (Lǚ) - The Treading",
    "泰 (Tài) - The Peace",
    "否 (Pǐ) - The Standstill",
    "同人 (Tóng Rén) - The Fellowship",
    "大有 (Dà Yǒu) - The Great Possessing",
    "谦 (Qiān) - The Modesty",
    "豫 (Yù) - The Enthusiasm",
    "随 (Suí) - The Following",
    "蛊 (Gǔ) - The Work on the Decayed",
    "临 (Lín) - The Approach",
    "观 (Guān) - The Contemplation",
    "噬嗑 (Shì Kè) - The Biting Through",
    "贲 (Bì) - The Grace",
    "剥 (Bō) - The Splitting Apart",
    "复 (Fù) - The Return",
    "无妄 (Wú Wàng) - The Innocence",
    "大畜 (Dà Chù) - The Taming Power of the Great",
    "颐 (Yí) - The Nourishment",
    "大过 (Dà Guò) - The Surpassing",
    "坎 (Kǎn) - The Abysmal",
    "离 (Lí) - The Clinging, Fire",
    "咸 (Xián) - The Influence",
    "恒 (Héng) - The Duration",
    "遁 (Dùn) - The Retreat",
    "大壮 (Dà Zhuàng) - The Power of the Great",
    "晋 (Jìn) - The Progress",
    "明夷 (Míng Yí) - The Darkening of the Light",
    "家人 (Jiā Rén) - The Family",
    "睽 (Kuí) - The Opposition",
    "蹇 (Jiǎn) - The Obstruction",
    "解 (Xiè) - The Deliverance",
    "损 (Sǔn) - The Decrease",
    "益 (Yì) - The Increase",
    "夬 (Guài) - The Breakthrough",
    "姤 (Gòu) - The Coming to Meet",
    "萃 (Cuì) - The Gathering Together",
    "升 (Shēng) - The Ascending",
    "困 (Kùn) - The Keeping Still, Mountain",
    "井 (Jǐng) - The Well",
    "革 (Gé) - The Cauldron",
    "鼎 (Dǐng) - The Taming Power of the Great",
    "震 (Zhèn) - The Arousing, Thunder",
    "艮 (Gèn) - The Keeping Still, Mountain",
    "渐 (Jiàn) - The Gentle, Wind",
    "归妹 (Guī Mèi) - The Joyous, Lake",
    "丰 (Fēng) - The Abundance",
    "旅 (Lǚ) - The Wanderer",
    "巽 (Xùn) - The Gentle, Wind",
    "兑 (Duì) - The Joyous, Lake",
    "涣 (Huàn) - The Dispersion",
    "节 (Jié) - The Duration",
    "中孚 (Zhōng Fú) - The Inner Truth",
    "小过 (Xiǎo Guò) - The Preponderance of the Small",
    "既济 (Jì Jì) - The After Completion",
    "未济 (Wèi Jì) - The Before Completion",
  ];