const positiveWiseKaomoji = [
    "٩(◕‿◕｡)۶",
    "(｡♥‿♥｡)",
    "(＾▽＾)",
    "٩(｡•́‿•̀｡)۶",
    "(•‿•)",
    "(°◡°♡)",
    "ʕ•ᴥ•ʔ",
    "(๑˃̵ᴗ˂̵)و",
    "(ᵔᴥᵔ)",
    "(o˘◡˘o)",
    "(✿◠‿◠)",
    "(^‿^)",
    "(´• ω •`)",
    "( ͡ᵔ ͜ʖ ͡ᵔ )",
    "(◕‿◕)",
    "(*^‿^*)",
    "｡◕‿◕｡",
    "ヾ(＾∇＾)",
    "٩(◕‿◕｡)۶",
    "(っ◔◡◔)っ",
    "( •_•)>⌐■-■",
    "(⌐■_■)",
    "(▰˘◡˘▰)",
    "ʕʘ̅͜ʘ̅ʔ",
    "ヾ(⌐■_■)ノ♪",
    "(＾ｖ＾)",
  ];
  export function randomKaomoji(){
  return positiveWiseKaomoji[Math.floor(Math.random() * positiveWiseKaomoji.length)]
  }
